doctrine:
       dbal:
           types:
               uuid_binary_ordered_time: Ramsey\Uuid\Doctrine\UuidBinaryOrderedTimeType
           mapping_types:
               uuid_binary_ordered_time: binary
